server:
  port: 8002

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: 4455
    jpa:
      open-in-view: false
      show-sql: false
      hibernate:
        ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.companyservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL?????
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: company-service # 每个服务不同命名
