server:
  port: 9001

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
