server:
  port: 8003

spring:
  application:
    name: jobseeker-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: jobseeker-service # 每个服务不同命名

