server:
  port: 8001

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 4455
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
